// <auto-generated />
using System;
using Employee_Management_System.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Employee_Management_System.Infrastructure.Migrations
{
    [DbContext(typeof(EMSDbContext))]
    [Migration("20200130105008_PopulateManagersOfDepartments")]
    partial class PopulateManagersOfDepartments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Employee_Management_System.Core.Entities.Department", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(254)")
                        .HasMaxLength(254);

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .HasName("Guid")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("ManagerId");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Description = "Logistics management is that part of the supply chain which plans, implements and controls the efficient, effective forward and reverse flow and storage of goods, services and related information between the point of origin and the point of consumption in order to meet customers' requirements.",
                            Email = "logistics@company.com",
                            Guid = new Guid("a9eb16c3-d4d6-4280-89ad-8e1bba35be38"),
                            Name = "Logistics",
                            PhoneNumber = "2101111111"
                        },
                        new
                        {
                            Id = (short)2,
                            Description = "Software Development team specializes in the development of custom software applications and offshore software outsourcing services.",
                            Email = "swdev@company.com",
                            Guid = new Guid("344ac739-b7ff-4b50-916b-77882688be7c"),
                            Name = "Software Development",
                            PhoneNumber = "2102222222"
                        },
                        new
                        {
                            Id = (short)3,
                            Description = "Human resources or HR is the department charged with finding, screening, recruiting, and training job applicants, and administering employee-benefit programs",
                            Email = "hr@company.com",
                            Guid = new Guid("8a113a93-2051-490d-9329-bad2920e9b97"),
                            Name = "Human Resources (HR)",
                            PhoneNumber = "2103333333"
                        });
                });

            modelBuilder.Entity("Employee_Management_System.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(254)")
                        .HasMaxLength(254);

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("HiringDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("JobId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("LatestSkillsetUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LatestUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .HasName("Guid")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("JobId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "george.papadimitriou@company.com",
                            Guid = new Guid("9dbc5eeb-6a83-46f9-92a4-23d8253f36cc"),
                            HiringDate = new DateTime(2019, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobId = (short)3,
                            LatestSkillsetUpdate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LatestUpdate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Georgios",
                            PhoneNumber = "2104444444",
                            Surname = "Papadimitriou"
                        },
                        new
                        {
                            Id = 2,
                            Email = "dimitrios.konstantinou@company.com",
                            Guid = new Guid("42bff182-7a27-4afb-b416-6ddec070a26f"),
                            HiringDate = new DateTime(2017, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobId = (short)5,
                            LatestSkillsetUpdate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LatestUpdate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dimitrios",
                            PhoneNumber = "2105555555",
                            Surname = "Konstantinou"
                        },
                        new
                        {
                            Id = 3,
                            Email = "eleni.dimitriou@company.com",
                            Guid = new Guid("a4c16623-aa97-4846-93e5-6fdd3c486f0f"),
                            HiringDate = new DateTime(2017, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobId = (short)2,
                            LatestSkillsetUpdate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LatestUpdate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eleni",
                            PhoneNumber = "2105555555",
                            Surname = "Dimitriou"
                        },
                        new
                        {
                            Id = 4,
                            Email = "john.dunham@company.com",
                            Guid = new Guid("2dcd69bf-d4bb-4964-afd0-5d6481a5028f"),
                            HiringDate = new DateTime(2017, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobId = (short)4,
                            LatestSkillsetUpdate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LatestUpdate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John",
                            PhoneNumber = "2106666666",
                            Surname = "Dunham"
                        },
                        new
                        {
                            Id = 5,
                            Email = "konstantina.nikolaou@company.com",
                            Guid = new Guid("14924b4e-8f1f-4221-b476-d850fb7147be"),
                            HiringDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobId = (short)6,
                            LatestSkillsetUpdate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LatestUpdate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Konstantina",
                            PhoneNumber = "2107777777",
                            Surname = "Nikolaou"
                        },
                        new
                        {
                            Id = 6,
                            Email = "amy.roberts@company.com",
                            Guid = new Guid("517f9706-11ca-4de9-8c94-05446aa07071"),
                            HiringDate = new DateTime(2017, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobId = (short)3,
                            LatestSkillsetUpdate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LatestUpdate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Amy",
                            PhoneNumber = "2108888888",
                            Surname = "Roberts"
                        },
                        new
                        {
                            Id = 7,
                            Email = "petros.stamatopoulos@company.com",
                            Guid = new Guid("ec458a9c-3abb-42ff-99dd-03e2ad93206d"),
                            HiringDate = new DateTime(2019, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobId = (short)3,
                            LatestSkillsetUpdate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LatestUpdate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Petros",
                            PhoneNumber = "2109999999",
                            Surname = "Stamatopoulos"
                        },
                        new
                        {
                            Id = 8,
                            Email = "katerina.kastriti@company.com",
                            Guid = new Guid("ce0de968-74e5-49cc-8f8b-e32b5ab6c8dc"),
                            HiringDate = new DateTime(2019, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobId = (short)1,
                            LatestSkillsetUpdate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LatestUpdate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Katerina",
                            PhoneNumber = "2101234567",
                            Surname = "Kastriti"
                        });
                });

            modelBuilder.Entity("Employee_Management_System.Core.Entities.EmployeeSkill", b =>
                {
                    b.Property<short>("SkillId")
                        .HasColumnType("smallint");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("SkillId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeSkill");

                    b.HasData(
                        new
                        {
                            SkillId = (short)1,
                            EmployeeId = 1
                        },
                        new
                        {
                            SkillId = (short)2,
                            EmployeeId = 1
                        },
                        new
                        {
                            SkillId = (short)4,
                            EmployeeId = 1
                        },
                        new
                        {
                            SkillId = (short)6,
                            EmployeeId = 1
                        },
                        new
                        {
                            SkillId = (short)7,
                            EmployeeId = 1
                        },
                        new
                        {
                            SkillId = (short)8,
                            EmployeeId = 1
                        },
                        new
                        {
                            SkillId = (short)9,
                            EmployeeId = 1
                        },
                        new
                        {
                            SkillId = (short)12,
                            EmployeeId = 1
                        },
                        new
                        {
                            SkillId = (short)14,
                            EmployeeId = 1
                        },
                        new
                        {
                            SkillId = (short)1,
                            EmployeeId = 2
                        },
                        new
                        {
                            SkillId = (short)2,
                            EmployeeId = 2
                        },
                        new
                        {
                            SkillId = (short)4,
                            EmployeeId = 2
                        },
                        new
                        {
                            SkillId = (short)5,
                            EmployeeId = 2
                        },
                        new
                        {
                            SkillId = (short)6,
                            EmployeeId = 2
                        },
                        new
                        {
                            SkillId = (short)7,
                            EmployeeId = 2
                        },
                        new
                        {
                            SkillId = (short)8,
                            EmployeeId = 2
                        },
                        new
                        {
                            SkillId = (short)9,
                            EmployeeId = 2
                        },
                        new
                        {
                            SkillId = (short)10,
                            EmployeeId = 2
                        },
                        new
                        {
                            SkillId = (short)11,
                            EmployeeId = 2
                        },
                        new
                        {
                            SkillId = (short)12,
                            EmployeeId = 2
                        },
                        new
                        {
                            SkillId = (short)13,
                            EmployeeId = 2
                        },
                        new
                        {
                            SkillId = (short)14,
                            EmployeeId = 2
                        },
                        new
                        {
                            SkillId = (short)1,
                            EmployeeId = 3
                        },
                        new
                        {
                            SkillId = (short)2,
                            EmployeeId = 3
                        },
                        new
                        {
                            SkillId = (short)3,
                            EmployeeId = 3
                        },
                        new
                        {
                            SkillId = (short)5,
                            EmployeeId = 3
                        },
                        new
                        {
                            SkillId = (short)13,
                            EmployeeId = 3
                        },
                        new
                        {
                            SkillId = (short)1,
                            EmployeeId = 4
                        },
                        new
                        {
                            SkillId = (short)2,
                            EmployeeId = 4
                        },
                        new
                        {
                            SkillId = (short)6,
                            EmployeeId = 4
                        },
                        new
                        {
                            SkillId = (short)7,
                            EmployeeId = 4
                        },
                        new
                        {
                            SkillId = (short)8,
                            EmployeeId = 4
                        },
                        new
                        {
                            SkillId = (short)9,
                            EmployeeId = 4
                        },
                        new
                        {
                            SkillId = (short)10,
                            EmployeeId = 4
                        },
                        new
                        {
                            SkillId = (short)11,
                            EmployeeId = 4
                        },
                        new
                        {
                            SkillId = (short)12,
                            EmployeeId = 4
                        },
                        new
                        {
                            SkillId = (short)13,
                            EmployeeId = 4
                        },
                        new
                        {
                            SkillId = (short)1,
                            EmployeeId = 5
                        },
                        new
                        {
                            SkillId = (short)4,
                            EmployeeId = 5
                        },
                        new
                        {
                            SkillId = (short)5,
                            EmployeeId = 5
                        },
                        new
                        {
                            SkillId = (short)13,
                            EmployeeId = 5
                        },
                        new
                        {
                            SkillId = (short)14,
                            EmployeeId = 5
                        },
                        new
                        {
                            SkillId = (short)1,
                            EmployeeId = 6
                        },
                        new
                        {
                            SkillId = (short)2,
                            EmployeeId = 6
                        },
                        new
                        {
                            SkillId = (short)4,
                            EmployeeId = 6
                        },
                        new
                        {
                            SkillId = (short)6,
                            EmployeeId = 6
                        },
                        new
                        {
                            SkillId = (short)7,
                            EmployeeId = 6
                        },
                        new
                        {
                            SkillId = (short)8,
                            EmployeeId = 6
                        },
                        new
                        {
                            SkillId = (short)9,
                            EmployeeId = 6
                        },
                        new
                        {
                            SkillId = (short)14,
                            EmployeeId = 6
                        },
                        new
                        {
                            SkillId = (short)1,
                            EmployeeId = 7
                        },
                        new
                        {
                            SkillId = (short)2,
                            EmployeeId = 7
                        },
                        new
                        {
                            SkillId = (short)4,
                            EmployeeId = 7
                        },
                        new
                        {
                            SkillId = (short)6,
                            EmployeeId = 7
                        },
                        new
                        {
                            SkillId = (short)7,
                            EmployeeId = 7
                        },
                        new
                        {
                            SkillId = (short)8,
                            EmployeeId = 7
                        },
                        new
                        {
                            SkillId = (short)9,
                            EmployeeId = 7
                        },
                        new
                        {
                            SkillId = (short)14,
                            EmployeeId = 7
                        },
                        new
                        {
                            SkillId = (short)1,
                            EmployeeId = 8
                        },
                        new
                        {
                            SkillId = (short)2,
                            EmployeeId = 8
                        },
                        new
                        {
                            SkillId = (short)4,
                            EmployeeId = 8
                        },
                        new
                        {
                            SkillId = (short)5,
                            EmployeeId = 8
                        },
                        new
                        {
                            SkillId = (short)13,
                            EmployeeId = 8
                        },
                        new
                        {
                            SkillId = (short)14,
                            EmployeeId = 8
                        });
                });

            modelBuilder.Entity("Employee_Management_System.Core.Entities.Job", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SeniorityLevel")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Guid")
                        .HasName("Guid")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("Job");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            DepartmentId = (short)1,
                            Description = "A logistics specialist is responsible for the oversight of the life cycle of products, including preparation, shipping and receiving.",
                            Guid = new Guid("7b75a444-994d-4936-96bf-9c3c0804e42d"),
                            SeniorityLevel = 1,
                            Title = "Logistics Specialist"
                        },
                        new
                        {
                            Id = (short)2,
                            DepartmentId = (short)1,
                            Description = "A logistics coordinator is responsible for managing all aspects of shipping routes and delivery, specifically with regard to customer satisfaction.",
                            Guid = new Guid("a51f9b12-fb95-43e2-b010-733d53faf235"),
                            SeniorityLevel = 2,
                            Title = "Logistics Coordinator"
                        },
                        new
                        {
                            Id = (short)3,
                            DepartmentId = (short)2,
                            Description = "A Junior Software Developer serves as a member of the software development team, aiding in the innovation and creation of company software and programs.",
                            Guid = new Guid("4d459461-59da-473d-938e-f5c7c03d12d7"),
                            SeniorityLevel = 0,
                            Title = ".NET Software Developer"
                        },
                        new
                        {
                            Id = (short)4,
                            DepartmentId = (short)2,
                            Description = "A Senior Software Developer serves as a leading member of the software development team, architecting towards innovation and creation of company software and programs.",
                            Guid = new Guid("5c4a34ac-be45-4419-8a8b-612c020b38cf"),
                            SeniorityLevel = 2,
                            Title = ".NET Software Developer"
                        },
                        new
                        {
                            Id = (short)5,
                            DepartmentId = (short)2,
                            Description = "IT Specialists, or Information Technology Specialists, install, monitor, and troubleshoot computer hardware and software systems.",
                            Guid = new Guid("905d1d8f-d286-4ef2-a72e-c76353f342cb"),
                            SeniorityLevel = 2,
                            Title = "IT Specialist"
                        },
                        new
                        {
                            Id = (short)6,
                            DepartmentId = (short)3,
                            Description = "A talent acquisition specialist is an HR professional who specializes in sourcing, identifying and hiring specific types of employees.",
                            Guid = new Guid("ca6a17f8-2045-4113-bbdb-3230427ae5cd"),
                            SeniorityLevel = 1,
                            Title = "Talent Acquisition Recruiter"
                        },
                        new
                        {
                            Id = (short)7,
                            DepartmentId = (short)3,
                            Description = "The responsibilities of human resources specialists revolve around the recruitment and placement of employees; therefore, their job duties may range from screening job candidates and conducting interviews to performing background checks and providing orientation to new employees.",
                            Guid = new Guid("d64e4e3c-6d5b-4818-9039-246861177572"),
                            SeniorityLevel = 2,
                            Title = "HR Specialist"
                        });
                });

            modelBuilder.Entity("Employee_Management_System.Core.Entities.JobSkill", b =>
                {
                    b.Property<short>("SkillId")
                        .HasColumnType("smallint");

                    b.Property<short>("JobId")
                        .HasColumnType("smallint");

                    b.HasKey("SkillId", "JobId");

                    b.HasIndex("JobId");

                    b.ToTable("JobSkill");

                    b.HasData(
                        new
                        {
                            SkillId = (short)1,
                            JobId = (short)1
                        },
                        new
                        {
                            SkillId = (short)2,
                            JobId = (short)1
                        },
                        new
                        {
                            SkillId = (short)5,
                            JobId = (short)1
                        },
                        new
                        {
                            SkillId = (short)13,
                            JobId = (short)1
                        },
                        new
                        {
                            SkillId = (short)14,
                            JobId = (short)1
                        },
                        new
                        {
                            SkillId = (short)1,
                            JobId = (short)2
                        },
                        new
                        {
                            SkillId = (short)2,
                            JobId = (short)2
                        },
                        new
                        {
                            SkillId = (short)5,
                            JobId = (short)2
                        },
                        new
                        {
                            SkillId = (short)1,
                            JobId = (short)3
                        },
                        new
                        {
                            SkillId = (short)2,
                            JobId = (short)3
                        },
                        new
                        {
                            SkillId = (short)4,
                            JobId = (short)3
                        },
                        new
                        {
                            SkillId = (short)6,
                            JobId = (short)3
                        },
                        new
                        {
                            SkillId = (short)7,
                            JobId = (short)3
                        },
                        new
                        {
                            SkillId = (short)8,
                            JobId = (short)3
                        },
                        new
                        {
                            SkillId = (short)9,
                            JobId = (short)3
                        },
                        new
                        {
                            SkillId = (short)14,
                            JobId = (short)3
                        },
                        new
                        {
                            SkillId = (short)1,
                            JobId = (short)4
                        },
                        new
                        {
                            SkillId = (short)2,
                            JobId = (short)4
                        },
                        new
                        {
                            SkillId = (short)6,
                            JobId = (short)4
                        },
                        new
                        {
                            SkillId = (short)7,
                            JobId = (short)4
                        },
                        new
                        {
                            SkillId = (short)8,
                            JobId = (short)4
                        },
                        new
                        {
                            SkillId = (short)9,
                            JobId = (short)4
                        },
                        new
                        {
                            SkillId = (short)10,
                            JobId = (short)4
                        },
                        new
                        {
                            SkillId = (short)11,
                            JobId = (short)4
                        },
                        new
                        {
                            SkillId = (short)12,
                            JobId = (short)4
                        },
                        new
                        {
                            SkillId = (short)13,
                            JobId = (short)4
                        },
                        new
                        {
                            SkillId = (short)1,
                            JobId = (short)5
                        },
                        new
                        {
                            SkillId = (short)2,
                            JobId = (short)5
                        },
                        new
                        {
                            SkillId = (short)4,
                            JobId = (short)5
                        },
                        new
                        {
                            SkillId = (short)5,
                            JobId = (short)5
                        },
                        new
                        {
                            SkillId = (short)8,
                            JobId = (short)5
                        },
                        new
                        {
                            SkillId = (short)11,
                            JobId = (short)5
                        },
                        new
                        {
                            SkillId = (short)13,
                            JobId = (short)5
                        },
                        new
                        {
                            SkillId = (short)14,
                            JobId = (short)5
                        },
                        new
                        {
                            SkillId = (short)1,
                            JobId = (short)6
                        },
                        new
                        {
                            SkillId = (short)4,
                            JobId = (short)6
                        },
                        new
                        {
                            SkillId = (short)5,
                            JobId = (short)6
                        },
                        new
                        {
                            SkillId = (short)13,
                            JobId = (short)6
                        },
                        new
                        {
                            SkillId = (short)14,
                            JobId = (short)6
                        },
                        new
                        {
                            SkillId = (short)1,
                            JobId = (short)7
                        },
                        new
                        {
                            SkillId = (short)2,
                            JobId = (short)7
                        },
                        new
                        {
                            SkillId = (short)3,
                            JobId = (short)7
                        },
                        new
                        {
                            SkillId = (short)13,
                            JobId = (short)7
                        });
                });

            modelBuilder.Entity("Employee_Management_System.Core.Entities.Skill", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .HasName("Guid")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("Skill");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            CreationDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Effective communication skills will be helpful through the interview process and in your career overall. The ability to communicate involves knowing how you should speak to others in different situations or settings.",
                            Guid = new Guid("57408e9a-9d0a-4df9-87df-fc4dbc8ab9e5"),
                            Name = "Communication",
                            Type = 1
                        },
                        new
                        {
                            Id = (short)2,
                            CreationDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Employers highly value people who can resolve issues quickly and effectively. That may involve calling on industry knowledge to fix an issue immediately as it occurs, or taking time to research and consult with colleagues to find a scalable, long-term solution.",
                            Guid = new Guid("6bd53075-c359-4723-88e6-e942d04af82b"),
                            Name = "Problem-solving",
                            Type = 1
                        },
                        new
                        {
                            Id = (short)3,
                            CreationDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Employees with creativity can find new ways to perform tasks, improve processes or even develop new and exciting avenues for the business to explore.",
                            Guid = new Guid("35534cb4-3e59-4edb-ab8d-da73caece421"),
                            Name = "Creativity",
                            Type = 1
                        },
                        new
                        {
                            Id = (short)4,
                            CreationDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Employees who are capable of adapting to new situations and ways of working are valuable in many jobs and industries.",
                            Guid = new Guid("d69b8478-b06a-4469-8540-4f0bffd9a3a1"),
                            Name = "Adaptability",
                            Type = 1
                        },
                        new
                        {
                            Id = (short)5,
                            CreationDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Work ethic is the ability to follow through on tasks and duties in a timely, quality manner. A strong work ethic will help ensure you develop a positive relationship with your employer and colleagues, even when you are still developing technical skills in a new job.",
                            Guid = new Guid("8a113a93-2051-490d-9329-bad2920e9b97"),
                            Name = "Work ethic",
                            Type = 1
                        },
                        new
                        {
                            Id = (short)6,
                            CreationDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Data Structures and Algorithms(e.g. array, linked list, tree) are the heart of programming as they improve the problem-solving ability of a candidate/employee to a great extent.",
                            Guid = new Guid("5dc15297-6522-4363-9c1f-c78b597eb73e"),
                            Name = "Data Structures and Algorithms",
                            Type = 0
                        },
                        new
                        {
                            Id = (short)7,
                            CreationDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Source control helps the developer in managing and storing their code.",
                            Guid = new Guid("1811edf9-c04b-4a09-80a9-8c28538a732c"),
                            Name = "Source Control (Git, TFS, etc.)",
                            Type = 0
                        },
                        new
                        {
                            Id = (short)8,
                            CreationDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "OOP defines most modern server-side scripting languages, which are the languages back-end developers use to write software and database technology.",
                            Guid = new Guid("caaf4435-c6de-436d-a941-8bf3f8d9ce38"),
                            Name = "OOP",
                            Type = 0
                        },
                        new
                        {
                            Id = (short)9,
                            CreationDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "C# is a general-purpose, multi-paradigm programming language encompassing strong typing, lexically scoped, imperative, declarative, functional, generic, object-oriented (class-based), and component-oriented programming disciplines.",
                            Guid = new Guid("7fde5249-3a4a-4b95-b8fc-81bc78cf848e"),
                            Name = "C#",
                            Type = 0
                        },
                        new
                        {
                            Id = (short)10,
                            CreationDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = ".NET Core is a free and open-source, managed computer software framework for Windows, Linux, and macOS operating systems. It is a cross-platform successor to .NET Framework.",
                            Guid = new Guid("99f337c3-175e-44b5-bb6f-c21daef9320c"),
                            Name = ".NET Core",
                            Type = 0
                        },
                        new
                        {
                            Id = (short)11,
                            CreationDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "SQL stands for Structured Query Language. SQL is used to communicate with a database.",
                            Guid = new Guid("b9d648ef-0199-4813-bb46-3edae60316fa"),
                            Name = "SQL",
                            Type = 0
                        },
                        new
                        {
                            Id = (short)12,
                            CreationDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Javascript often abbreviated as JS, is a high-level, just-in-time compiled, multi-paradigm programming language that conforms to the ECMAScript specification.",
                            Guid = new Guid("6bf0ba43-52eb-42b3-8e7e-e956813d0030"),
                            Name = "Javascript",
                            Type = 0
                        },
                        new
                        {
                            Id = (short)13,
                            CreationDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Forward thinking helps you make accurate predictions of the possible needs of your company, as well as outcomes of actions made anywhere in the entire supply chain.",
                            Guid = new Guid("f297e677-4614-41a6-8899-244205ef2f61"),
                            Name = "Forward Thinking",
                            Type = 1
                        },
                        new
                        {
                            Id = (short)14,
                            CreationDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "When it comes to working with other teams or units in the supply chain, it pays to treat everyone with respect and professionalism.",
                            Guid = new Guid("53417bc5-a7c1-4bad-8393-78d79b263270"),
                            Name = "Team player",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Employee_Management_System.Core.Entities.Department", b =>
                {
                    b.HasOne("Employee_Management_System.Core.Entities.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");
                });

            modelBuilder.Entity("Employee_Management_System.Core.Entities.Employee", b =>
                {
                    b.HasOne("Employee_Management_System.Core.Entities.Job", "Job")
                        .WithMany("Employees")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Employee_Management_System.Core.Entities.EmployeeSkill", b =>
                {
                    b.HasOne("Employee_Management_System.Core.Entities.Employee", "Employee")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Employee_Management_System.Core.Entities.Skill", "Skill")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Employee_Management_System.Core.Entities.Job", b =>
                {
                    b.HasOne("Employee_Management_System.Core.Entities.Department", "Department")
                        .WithMany("Jobs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Employee_Management_System.Core.Entities.JobSkill", b =>
                {
                    b.HasOne("Employee_Management_System.Core.Entities.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Employee_Management_System.Core.Entities.Skill", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
